
export default {
    GET_HOLIDAYS_PENDING: "GET_HOLIDAYS_PENDING_ACTION",
    GET_HOLIDAYS_SUCCESS: "GET_HOLIDAYS_SUCCESS_ACTION",

    // UPDATE_FOLLOW_HOLIDAY: "UPDATE_FOLLOW_HOLIDAY_ACTION"
    UPDATE_FOLLOW_HOLIDAY_SUCCESS: "UPDATE_FOLLOW_HOLIDAY_ACTION",  

};

